language: python
python:
  - "3.6"

services:
  - postgresql

before_script:
  - psql -c "create database noise;" -U postgres
  - sudo aptitude -y -q install libcairo2-dev libpixman-1-dev libpango1.0-dev libgif-dev libjpeg-dev libgtk2.0-dev vlc libvlc-dev portaudio19-dev libsqlite3-dev libcurl4-openssl-dev makeself curl

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - python noise/manage.py migrate
  - bundle exec rake && bundle exec rake features
  - coverage run noise/manage.py test noise

after_success:
  - coveralls

notifications:
  email: false

rvm: 1.9.2
