# Generated by Django 2.0.5 on 2018-05-21 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=100, null=True)),
                ('path', models.FileField(upload_to='clips/')),
                ('date_published', models.DateField(blank=True, null=True)),
                ('published', models.CharField(choices=[('PUB', 'Published'), ('UNPUB', 'Unpublished')], max_length=12)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='audio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
