# Generated by Django 2.0.5 on 2018-05-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise_audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='published',
            field=models.CharField(choices=[('PUB', 'Published'), ('UNPUB', 'Unpublished')], default='UNPUB', max_length=12),
        ),
    ]
