# Generated by Django 2.0.5 on 2018-05-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise_audio', '0003_auto_20180521_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='concat_path',
            field=models.FileField(blank=True, null=True, upload_to='concat/'),
        ),
    ]
