# Generated by Django 2.0.5 on 2018-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noise_audio', '0004_audio_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='concat_file',
            field=models.FileField(blank=True, null=True, upload_to='concat/'),
        ),
    ]
