# Generated by Django 2.0.5 on 2018-05-24 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noise_audio', '0005_audio_concat_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='temp/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='audio',
            name='concat_file',
        ),
        migrations.AddField(
            model_name='audioadd',
            name='pk_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pk_master', to='noise_audio.Audio'),
        ),
        migrations.AddField(
            model_name='audioadd',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
